import type { Metadata } from "next";
import { Geist, Geist_Mono, Aclonica } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";
import Navbar from "@/components/share/Navbar";

const aclonica = Aclonica({
  variable: "--font-aclonica",
  subsets: ["latin"],
  weight: ["400"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const game = LocalFont({
  src: [{ path: "../../public/fonts/PressStart2P-Regular.ttf" }],
  variable: "--font-game",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${game.variable} ${aclonica.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
